### ISSUE TITLE
Adding new "type" values

### ISSUE THREAD

**Issue by yujoy** [singer-io/tap-google-search-console#25]
Google recently added a few new search type values (`discover`, `googleNews`, and `news`), as well as beginning to deprecate `searchType` in favor of `type`. [Documentation here](https://developers.google.com/search/blog/2021/10/search-analytics-discover-gnews).

Can we add these new types to iterate through and include in the response?

**Comment by HiteshES** [comment]
Yes, right now we have performance report only for search. It will be helpful to get Discover, News too

**Comment by kethan1122** [comment]
We have released it as part of our recent release(v1.0.0).
